export const authTypes = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGOUT: 'LOGOUT',
    IS_LOGIN: 'IS_LOGIN',
    SET_AUTH_REDIRECT_PATH: 'SET_AUTH_REDIRECT_PATH',
    GET_USER: 'GET_USER',
    IS_PROVIDER: 'IS_PROVIDER',
}