export const serviceActionTypes = {
    FETCH_SERVICES: 'FETCH_SERVICES',
    REQUEST_SERVICES: 'REQUEST_SERVICES',
    CAT_SERVICES: 'LOADING_SERVICES',
    ERROR_SERVICES: 'ERROR_SERVICES',
    LOAD_MORE_SERVICES: 'LOAD_MORE_SERVICES',
}