export const reqTypes = {
    START_REQUEST : 'START_REQUEST',
    SUCCESS_REQUEST : 'SUCCESS_REQUEST',
    FAIL_REQUEST : 'FAIL_REQUEST',
    FETCH_START: 'FETCH_START',
    SUCCESS_FETCH: 'SUCCESS_FETCH',
    ERROR_FETCH: 'ERROR_FETCH',
    GET_SINGLE: 'GET_SINGLE'
}