export const serviceTypes = {
    REQUEST_SERVICES: 'REQUEST_SERVICES',
    SUCCESS_SERVICES: 'SUCCESS_SERVICES',
    FAIL_SERVICES: 'FAIL_SERVICES',
}

export const savingServiceTypes = {
    SEND_REQUEST: 'SEND_REQUEST',
    REQUEST_SUCCESS: 'REQUEST_SUCCESS',
    REQUEST_FAIL: 'REQUEST_FAIL'
}

export const singleServiceTypes = {
    REQUEST_SERVICE: 'REQUEST_SERVICE',
    SERVICE_SUCCESS: 'SERVICE_SUCCESS',
    FAIL_SERVICE: 'FAIL_SERVICE'
}