export const Api = {
    LOGIN: '/api/login',
    REGISTER: '/api/register',
    USER: '/api/user',
    ALLSERVICES: '/api/services1',
    SAVE_SERVICE: '/api/add/service-provider',
    SERVICE_CATEGORIES: '/api/categories',
    SERVICES_PAGINATED: 'api/services',
    CATEGORY_SERVICES: '/api/servicess',
    MAKE_SERVICE_REQUEST: '/api/request',
    SERVICE_PROVIDERS: '/api/providers',
    OFFER: '/api/bid',
    ALL_REQUESTS: '/api/all-requests',
    CATEGORY_REQUESTS: '/api/cat-requests',
    BID: '/api/bid',
    UPDATE_PROFILE: '/api/user/profile/update?=',
    UPDATE_PASSWORD: '/api/user/password/update',
    MANAGE_TASKS: '/api/services/user/requests',
    MANAGE_BIDDERS: '/api/my-offers',
    MANAGE_ACTIVE_BIDS: '/api/my-offers',
    EMPLOYERS_REQUESTS: '/api/services/user/requests',
    MY_REQUESTS: '/api/my-requests',
    MAKE_OFFER_TO_SERVICE_PROVIDER: '/api/make-offer',
    UNCANCELLED_SERVICES: '/api/services/requests/false/cancelled',
    EMPLOYERS_REQUESTS: '/api/services/user/requests',
    MY_REQUESTS: '/api/my-requests',
    SERVICE_REQUEST_OFFERS: 'api/delivery/requests/services/offers/id'
}